-- Voice-conversational layer — schema additions.
--
-- Two new tables ride alongside the existing `runs` / `agent_outputs` schema
-- (see web/db.py). They are referenced by `web/voice/db.py` (Python) and the
-- voice agent worker (`tradingagents/voice/agent_worker.py`).
--
-- Both tables are write-mostly and fail-open from the app: if these tables are
-- missing or RLS denies a write, the voice session still runs — it just lacks
-- a persisted transcript and the daily-minute cost guardrail degrades to
-- "unenforced". So this migration is safe to apply lazily: existing data is
-- never touched.
--
-- Apply via the Supabase SQL editor or `supabase db push`.

-- ──────────────────────────────────────────────────────────────────────────
-- voice_sessions — one row per call.
--
-- The session id is generated by the API (`web/voice/router.py`) and re-used
-- as the LiveKit room suffix, so it appears verbatim in client telemetry and
-- LiveKit logs.
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.voice_sessions (
    id                      text primary key,
    run_id                  text not null,
    agent_id                text not null,
    user_id                 text,
    livekit_room            text not null,
    status                  text not null default 'started',
    error                   text,

    -- persona snapshot (the voice id we *actually* used, even if the persona
    -- spec changes later — important for cost/voice audit trails)
    persona_voice_id        text,
    persona_voice_name      text,

    -- providers
    tts_provider            text,
    asr_provider            text,
    llm_provider            text,
    llm_model               text,

    -- timing
    started_at              timestamptz not null default now(),
    ended_at                timestamptz,

    -- usage rollups (also queried by user_voice_minutes_today for the daily
    -- minute cap, so an index on (user_id, started_at) keeps that hot path
    -- fast even after millions of rows)
    input_audio_seconds     double precision not null default 0,
    output_audio_seconds    double precision not null default 0,
    input_tokens            integer not null default 0,
    output_tokens           integer not null default 0,
    cost_usd                double precision not null default 0
);

create index if not exists voice_sessions_run_idx       on public.voice_sessions (run_id);
create index if not exists voice_sessions_user_time_idx on public.voice_sessions (user_id, started_at desc);
create index if not exists voice_sessions_started_idx   on public.voice_sessions (started_at desc);

-- ──────────────────────────────────────────────────────────────────────────
-- voice_turns — one row per finalized ASR or TTS turn (plus the "reconcile"
-- one-shot rationale updates from `tradingagents/voice/reconcile.py`).
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.voice_turns (
    id            bigserial primary key,
    session_id    text not null
                  references public.voice_sessions(id) on delete cascade,
    idx           integer not null,
    role          text not null check (role in ('user', 'assistant', 'reconcile')),
    text          text not null,
    provider      text,
    model         text,
    started_at    timestamptz,
    ended_at      timestamptz,
    created_at    timestamptz not null default now(),
    -- A session's turns are queried ordered by idx; uniqueness defends
    -- against the worker double-inserting on a retry.
    unique (session_id, idx)
);

create index if not exists voice_turns_session_idx_idx on public.voice_turns (session_id, idx);

-- ──────────────────────────────────────────────────────────────────────────
-- Row-level security: gate writes through the service-role key the backend
-- uses (web/db.py), and grant authenticated users read access to their own
-- sessions only. Adjust `auth.uid()` matching if you store user_id as a
-- non-UUID string.
-- ──────────────────────────────────────────────────────────────────────────
alter table public.voice_sessions enable row level security;
alter table public.voice_turns    enable row level security;

-- Service role bypasses RLS by default; explicit policies are for the
-- authenticated client (which we currently DO NOT use for these tables, but
-- this keeps the door open for a "my voice history" UI without changing the
-- migration).
do $$ begin
    create policy "voice_sessions_self_read"
        on public.voice_sessions for select
        using (user_id = auth.uid()::text);
exception when duplicate_object then null; end $$;

do $$ begin
    create policy "voice_turns_self_read"
        on public.voice_turns for select
        using (
            session_id in (
                select id from public.voice_sessions where user_id = auth.uid()::text
            )
        );
exception when duplicate_object then null; end $$;
